@host = http://localhost:3000

# get journals
GET {{host}}/journals

### get journals with filter
GET {{host}}/journals?max=5

### get journal title A
GET {{host}}/journals/A


### get inspections
GET {{host}}/inspections

### get inspections
GET {{host}}/inspections?city=new%20york

### get inspections
GET {{host}}/inspections?city=new%20york&sector=Cigarette%20Retail%20Dealer%20-%20127

### get inspections
GET {{host}}/inspections/cities

### get sectors
GET {{host}}/inspections/sectors





